### ISSUE TITLE
Checklist for 1.0.0

### ISSUE THREAD

**Issue by emiasims** [milisims/tree-sitter-org#13]
With the changes in the current `markup-redo` branch, I'd like to pause before integration (primarily understanding orgmode.nvim uses the main branch) to have some discussion about the work here, and compile a 1.0 checklist.

### Changes to markup
To start, thoughts on changes in the `markup-redo` branch. The first big one is that all markup parsing is completely removed, and in place of processing text as hidden nodes, whitespace delimited words are now parsed as `(expr)` nodes. An expression here is parsed first for looking for ascii symbols as hidden nodes, then letters as `"str"`, then numbers as `"num"`, and finally any remaining symbols as `"sym"`.

The reasoning for this set up is first that anything parsed in the parser is unchangeable, so markup was difficult to customize, and if a user wanted to add another link style (such as markdown-style links), they were unable to do so. Now, they just need to write queries and no modification for the parser is required.

For example, `a (*b1 cdef*)` is parsed to `(expr) (expr) (expr)` and when looking at hidden nodes, `(expr "str") (expr "(" "*" "str" "num") (expr "str" "*" ")")`. Which we can query for in a variety of ways. Unfortunately, a major caveat for this is the fact that tree-sitter queries capture exactly one node (see tree-sitter/tree-sitter#1508), so capturing alone (without writing a directive or callback of some sort) will not be able to highlight markdown as is. Additionally, we need to account for nested expressions.

The other major caveat is that anonymous nodes are unable to be anchored (tree-sitter/tree-sitter#1461), so we can't make the queries as precise as I would like right now, but single node queries can just use the `#match?` predicate so I'm not worried about that.

The positive side of this is that because the markup characters will be hidden nodes, they are _easily queried for_ and whatever algorithm is applied will generally only need to look at _very_ few nodes. Any language should be able to do that very quickly. Queries to find _possible pairs_ are in the branch in the `markup.scm` file, and I'm working the kinks out of a lua implementation of this pseudocode:
``` python
def markup(nodes):
    # assumes sorted list of nodes
    # all nodes should be from a single (paragraph), (itemtext), or (item)

    seeking = []
    markup = []
    for node in nodes:
        if node.type == start:
            seeking.append((node.type, node))
        elif node.type in seeking:
            ix = seeking.index(node.type)
            stnode = seeking[ix][1]
            if validate(node, stnode):  # check the pre/post markup or whatever else, can be modified as desired
                # stop seeking everything after the node we just matched: *a /b*    Like this '/', when we just matched the * after the b
                seeking = seeking[:ix-1]
                # If we complete a verbatim-style markup, we need to purge everything interior of it
                markup.append({'type': node.type, 'range': (stnode.start, node.end)})
    return markup
```
The details of this algorithm will change depending on exactly which node is captured (The symbol vs `(expr)`) and whether or not we're using `match` predicate in advance. My example does not do that, but after writing my lua example I'm thinking it makes sense to do so.

Note how easily constructed the markup queries are via some generative code for customization.

Lastly, queries/algorithms are needed for latex fragments, subscript and superscript, and bracketed expressions for the *scripts.

### Regex patterns
I still need to work through the list of changes I made, but one change I've made/am still making to the markup branch is I've tried replacing specific patterns as often as possible with some variant of `(expr)`. I think using queries to determine if a propery plan name is used, for example, is much cleaner than throwing a parser error. And this way it's easier to change languages. I think there are limits though, and it might be nice to simply support different languages in the parser directly (for example, `END`, `PROPERTIES`, etc.). That could be read from a file, or simply left for others to re-compile to their own language.

Additionally, queries are highlighting, so allowing more things to be specified as queries nicely can be pretty cool. For example, I might only ever use `TITLE` and `FILETAGS` directives, so I could consider highlighting those nicely and any other patterns as an error. 

A good example here is timestamp contents. Right now, I've hard coded possible regex expressions. Should that just be queriable? That could be nice if people want different formats. On the other hand, having fields and nodes directly in the tree is really nice, and I think in timestamps there are few enough formats that we can just support all of them in the parser.

### Fields and nodes/aliases
When writing the parser I didn't add a lot of fields because it was constantly in so much flux. But they're useful even if they link directly to a named node with the same name, because access via a name can be a lot more convenient than named nodes, even if there is a small number of nodes.

I've added a large number of `(name)` nodes, and a few others, and many fields. I'll try to compile a list later today. When thinking about where I've added nodes, one of the things I was thinking about was incremental selection via nodes, I just want it to make sense. For example, tag -> taglist -> item -> headline -> section.

### Versioning
These changes were a lot more than I'd like to do in a single commit or merge in the future, but since I was writing queries as I went, I kept finding small changes that make using the parser a lot more straightforward. I don't work on coding projects that are public really, so I don't think much about this, so this is kind of a "Yeah, why didn't you do that sooner?" section.

So AFTER 1.0.0, I'll be using consistent [conventional commits](https://www.conventionalcommits.org) in the future and an auto-updating semantic versioning system based on that. With `major.minor.patch` versioning: `fix` changes increment `patch`, `feat` changes increment `minor`, and any breaking change (appending a `!` to the scope) will increment major versioning. I just want to make sure anything using the parser has a tag that they can link to so changes can be made to `main` without breaking dependent projects.

### Specific questions
  - Are there any missing/hidden aliases or fields that would be useful?
  - Are the _names_ of aliases and fields sensible?
  - Should newlines be part of `(body)`? (Newlines before body in `(section)` and in `(document)`)
    So, should an empty section have a body, basically, or should a body exist only if there is an
    element?
  - If we have text that is a paragraph followed by a footnote after a new line, is that parsed in
    emacs as a footnote reference or a definition?
  - Should `(_element)` be available to `listitem`s and in drawer contents, or should those just be
    `expr`essions? I'm under the impression that whether or not elements are in a list and drawer
    are customizable options for orgmode, and I prefer to keep the parser simple as possible. So it
    makes sense to me to inject an org parser in the `itemtext` if a user wants it.
  - Should `(taglist)` be a named node?

### 1.0.0 checklist
I want to expand upon this list (some items should be multiple), but really quickly:
  - [x] Revisit all tests - A lot are out of date
  - ~~[ ] Write tests for queries~~
  - [x] Fix some regexes to better query for: :block: is the whole name, the goal would be ':', (name), ':'. (easier highlighting ':'s)
  - ~~[ ] Cleanup table precedences. Yikes. (I don't care anymore)~~
  - ~~[ ] Add semantic versioning git hook script~~
  - [x] Revisit the readme build instructions
  - [x] Revisit the npm dependencies (could really use some help here, no idea what I'm doing there)
  - [x] Add plan entries
  - [x] Add newlines to `(contents)` and `(body)`
  - [x] Fix failing headline test

Thoughts? Anything else I'm missing?

**Comment by kristijanhusak** [comment]
Thanks for your hard work on this. I'm hoping we will solve the remaining parsing issues with this release. 

### Changes to markup
This looks ok to me, from what I understand. I'm not sure when I will fully switch to this because of the Conceal limitation, but I'm hoping it will happen at some time.

### Regex patterns
> A good example here is timestamp contents. Right now, I've hard coded possible regex expressions. Should that just be queriable? That could be nice if people want different formats. On the other hand, having fields and nodes directly in the tree is really nice, and I think in timestamps there are few enough formats that we can just support all of them in the parser.

I think what we currently have in main is sufficient. No one really reported any issues regarding this, and I had variety of people using this (From Japan to Spain to USA).  would especially avoid this if it will slow down the parser.

### Fields and nodes/aliases
I think this is ok, I don't see any bigger issues with it.

### Versioning
I'm completely in for this. That last commit broke plan parsing, and I manage to catch it before reports started coming in. Having fixed releases would help me a lot.

### My answers to questions

I'll try to answer some of these questions:
> Are there any missing/hidden aliases or fields that would be useful?

It's a bit hard at this time to grasp what was changed, but if none of the currently available named nodes were removed, I think it's ok. I saw that structure is changed, so I will definitely need to do some work on adapting this.
One thing I noticed with the latest commit on main branch is that plan timestamps are a bit tricky to be parsed. Maybe nesting the name->timestamp would be easier to parse. For example, this content:
```
* TODO Test
  DEADLINE: <2021-12-04 Sat> <2021-12-05 Sun>
```

Returns something like this (I handwritten this):
```
plan:
  type: name
  datetime: timestamp
  datetime: timestamp
```
For this, in agenda view, I need to show the deadline date for today, and for tomorrow I need to show an entry just like a plain date. Parsing is tricky because everything is on the same level, so when I get to the timestamp, i need to check if previous node is a "type", and act on that accordingly. I would love to have plan dates nested to something like this:
```
 plan:
   plan_entry:
     type: name
     datetime: timestamp
   timestamp
```
`plan_entry` is probably not appropriate, but that's what I come up with at this moment.  So if it's only a timestamp, I know it's just a plain date, and if it's plan_entry, I know what to do with it.

Similar thing is with date ranges. With this:
```
<2021-12-04 Sat 17:48>--<2021-12-06 Sat 17:48>
```
I get something like this:
```
timestamp:
  date
  time
  date
  time
```
I would love to be able to know this is a date range and properly distinguish between start and end. Currently my parsing is a bit hacky, but it works. One issue for my case could be that I'm trying to avoid doing queries, because I noticed that neovim can be sometimes slow when doing them. I'm mostly doing `node:iter_children()` and handle it from there. Not ideal, but it's the fastest way at this moment.

> Are the names of aliases and fields sensible?

From what I see, they are fine.. I didn't had any specific issues with it until now.

> Should newlines be part of (body)? (Newlines before body in (section) and in (document))
> So, should an empty section have a body, basically, or should a body exist only if there is an
> element?
 
If by `empty section` you mean having empty lines in body:
```
* TODO I have empty body

* TODO Second
```
I'd rather have a body. But if you mean just a one liner, I don't think it makes sense.

> If we have text that is a paragraph followed by a footnote after a new line, is that parsed in
emacs as a footnote reference or a definition?

I don't know answer to this, but I can probably test how emacs behave.

> Should (_element) be available to listitems and in drawer contents, or should those just be
expressions? I'm under the impression that whether or not elements are in a list and drawer
are customizable options for orgmode, and I prefer to keep the parser simple as possible. So it
makes sense to me to inject an org parser in the itemtext if a user wants it.

Currently I'm manually parsing drawer content (logbook), and I guess that's fine. Having `_element` in there would not help be a lot, so if this simplifies things, go for it.

> Should (taglist) be a named node?

I don' think it's needed. Having `(tag)` is sufficient for me.

### Checklist

> Revisit the npm dependencies (could really use some help here, no idea what I'm doing there)

I don't think you need to worry about this too much. If you want, you can probably just do `npm update` and let it update to the latest version, but I don't think it's necessary at this point.

### Testing

I don't know if this is ready or not, but I gave this a quick test. It errored out immediately when I opened the file. At first I thought it's caused by my plugin, but it seems highlighting and tsplayground have some issues. 

This is the error I get when I disable TS highlighting for org filetype, and I try to open ts playground:
![screenshot](https://i.imgur.com/capS2VM.png)

Almost the same error appears when I try to enable TS highlights, just the stack trace is slightly different.

My assumption is that it's not ready yet, but I wanted to test if that will help you at all.

**Comment by emiasims** [comment]
I've tagged the current main branch as `v0.1.0`, so if you update dependencies to expect the tag we can prevent too many breaking updates for users. Keeping that in mind, I'll wait another week or so before pushing any updates to main so the change to depending on a specific tag can propagate through.

I'll probably roll in the updates to plans and body newlines to the same tag as the markup-redo merge, because it's mostly done. `v1.0.0` should follow quickly after, as soon as I revisit the tests and check off the list.

**Comment by kristijanhusak** [comment]
I updated the readme to point to specific commit , since setting a tag in the `revision` is not working properly (nvim-treesitter cannot parse folder with tag).
Regarding the test I did, is that something that needs to be fixed or I had some issue on my side?

**Comment by emiasims** [comment]
> I updated the readme to point to specific commit , since setting a tag in the `revision` is not working properly (nvim-treesitter cannot parse folder with tag).

Is it that tags are not supported, or that I used a lightweight tag, which just points at a revision instead of creating a commit itself (annotated tag)?

> Regarding the test I did, is that something that needs to be fixed or I had some issue on my side?

Opening this identical file on my end works fine, with both branches.

**Comment by kristijanhusak** [comment]
> Is it that tags are not supported, or that I used a lightweight tag, which just points at a revision instead of creating a commit itself (annotated tag)?

When setting a revision, you need to set as `v0.1.0`, but it downloads tar.gz as `tree-sitter-0.1.0`, and it doesn't know how to copy the compiled `org.so` because `v0.1.0` is not matching `0.1.0`. 

> Opening this identical file on my end works fine, with both branches.

I removed orgmode plugin and it opened without any errors, so I assume something is causing it there to break. Thanks.

> I'll probably roll in the updates to plans and body newlines to the same tag as the markup-redo merge, because it's mostly done.

How different will this be from the current structure? Should I wait or I can start preparing the migration to the new structure?

**Comment by kristijanhusak** [comment]
Seems like update wasn't so complicated. I just tweaked few queries and it made 90% of the things work. I'm only left with the dates parsing that you plan to change. Keep me posted.

**Comment by lukas-reineke** [comment]
With this, unchecked checkboxes `[ ]` get split into two `expr`. `[` and ` ]`
This would make it really difficult to work with.

**Comment by kristijanhusak** [comment]
@lukas-reineke Are you sure? From what I see, there's still a [node](https://github.com/milisims/tree-sitter-org/blob/markup-redo/grammar.js#L245) for it in grammar.

**Comment by lukas-reineke** [comment]
![Screen Capture_select-area_20211224195204](https://user-images.githubusercontent.com/12900252/147346728-3c2431e7-014b-4c98-9cd1-dbf8b63eb266.png)
yeah, it gets parsed like this

**Comment by emiasims** [comment]
Pushed a few changes to the branch, should resolve most issues. 

Right now there's a failing test for where a headline item looks like a tag list, like `* :a: b`, but should just be `(item)`. Not really sure what's going on there yet, but it's pretty low priority for me for now, since the only time it seems to happen is where there's a complete-looking taglist (`:a:` or `:a:b:`) followed by some non-tag text, I'm not really worried about it. These work just fine: `* a :b: c`, `* :a b:`.

**Comment by kristijanhusak** [comment]
Awesome! I'll take a look at it next week.

**Comment by kristijanhusak** [comment]
Seems like timestamps are not parsed outside of the "plan" line. Example content:
```
* TODO Test
  DEADLINE: <2022-01-11 Tue 11:00>
  Some content
  <2022-01-11 Tue 11:00>
  More content after
```

Output:
```
(document [0, 0] - [5, 0]
  (section [0, 0] - [5, 0]
    (headline [0, 0] - [1, 0]
      stars: (stars [0, 0] - [0, 1])
      item: (item [0, 2] - [0, 11]
        (expr [0, 2] - [0, 6])
        (expr [0, 7] - [0, 11])))
    (plan [1, 2] - [2, 0]
      (entry [1, 2] - [1, 34]
        type: (expr [1, 2] - [1, 10])
        timestamp: (timestamp [1, 12] - [1, 34]
          (date [1, 13] - [1, 23])
          (day [1, 24] - [1, 27])
          (time [1, 28] - [1, 33]))))
    (body [2, 2] - [5, 0]
      (paragraph [2, 2] - [5, 0]
        (expr [2, 2] - [2, 6])
        (expr [2, 7] - [2, 14])
        (expr [3, 2] - [3, 13])
        (expr [3, 14] - [3, 17])
        (expr [3, 18] - [3, 24])
        (expr [4, 2] - [4, 6])
        (expr [4, 7] - [4, 14])
        (expr [4, 15] - [4, 20])))))
```

**Comment by emiasims** [comment]
That's correct, I'm going to keep them out since they fall under markup, more or less. They're easily added with any system that can parse emphasis markers with queries.

**Comment by kristijanhusak** [comment]
> they fall under markup, more or less
They fall under markup context wise, but they are read for other purposes:

* Agenda shows these dates on the day they occur (active ones)
* Logbook times needs to be parsed in order to properly allow clock in/clock out/recalculating totals

Having them parsed would be really beneficial for me. Are there any downsides from adding regular nodes for them?

**Comment by emiasims** [comment]
Heads up for a squash and merge tomorrow for v0.2.

Adding nodes for them would make their customization impossible which is the whole point of this change, and I really don't see those two points as strong enough to break the everything is an `(expr)` paradigm, for two reasons: they're easy enough to find on their own, and agenda and logbooks are features not everyone uses, I certainly don't.

**Comment by kristijanhusak** [comment]
Ok, I'll adapt to the change. I had manual parsing of dates before the TS, so I can just reuse that.

**Comment by lukas-reineke** [comment]
> they're easy enough to find on their own

this is probably just my lack of treesitter knowledge, but how do you determine the type of a node without parsing the text outside of treesitter?
I understand you can add expressions in a query, but how does it work if you only have the node? Or say want to know the type of the parent?

**Comment by kristijanhusak** [comment]
I'm getting a parsing error where I don't expect it.
This content:
```
#+TITLE: Some file
* TODO SOME TODO :FIRSTTAG:SECONDTAG:THIRDTAG:
** TODO Child
child
*** THIRD CHILD
  another child
```

Gives this:
```
(document [0, 0] - [6, 0]
  (body [0, 0] - [1, 0]
    directive: (directive [0, 0] - [1, 0]
      name: (expr [0, 2] - [0, 7])
      value: (value [0, 9] - [0, 18]
        (expr [0, 9] - [0, 13])
        (expr [0, 14] - [0, 18]))))
  (section [1, 0] - [6, 0]
    (headline [1, 0] - [2, 0]
      stars: (stars [1, 0] - [1, 1])
      item: (item [1, 2] - [1, 16]
        (expr [1, 2] - [1, 6])
        (expr [1, 7] - [1, 11])
        (expr [1, 12] - [1, 16]))
      tags: (tag_list [1, 17] - [1, 46]
        tag: (tag [1, 18] - [1, 26])
        tag: (tag [1, 27] - [1, 36])
        tag: (tag [1, 37] - [1, 45])))
    (section [2, 0] - [6, 0]
      (headline [2, 0] - [3, 0]
        stars: (stars [2, 0] - [2, 2])
        item: (item [2, 3] - [2, 13]
          (expr [2, 3] - [2, 7])
          (expr [2, 8] - [2, 13])))
      (ERROR [3, 0] - [3, 5]
        (expr [3, 0] - [3, 5]))
      (body [3, 5] - [4, 0])
      (section [4, 0] - [6, 0]
        (headline [4, 0] - [5, 0]
          stars: (stars [4, 0] - [4, 3])
          item: (item [4, 4] - [4, 15]
            (expr [4, 4] - [4, 9])
            (expr [4, 10] - [4, 15])))
        (ERROR [5, 2] - [5, 15]
          (expr [5, 2] - [5, 9])
          (expr [5, 10] - [5, 15]))
        (body [5, 15] - [6, 0])))))
```
```

**Comment by emiasims** [comment]
> this is probably just my lack of treesitter knowledge, but how do you determine the type of a node without parsing the text outside of treesitter? I understand you can add expressions in a query, but how does it work if you only have the node? Or say want to know the type of the parent?

You do need to have a secondary parser, and I'm finding the best solution is to re-parse the whole element node (`paragraph`, list `itemtext`, headline `item` text), and not using the built-in highlighter. That allows you to parse only one paragraph at a time and leave extmarks on all other nodes for highlighting.

You're not parsing the whole of the text though, just looking for special signifiers. For example for timestamps, you might do `((expr '<' @ts.open) (expr '>' @ts.close) (#org-is-timestamp? @ts.open @ts.close) (#org-set-ts-range! @ts.open @ts.close)`. The is-timestamp predicate would check to confirm the range from the captured '<' and '>' match the definition of a timestamp (probably regex), and then the ts-range predicate would set metadata on the `@ts.open` capture to the full range. That last part is necessary tree-sitter can only capture nodes, which doesn't necessarily exist for a range of text.

This might seem like a lot, but to me this feels so much better after writing code to do the parsing that isn't within tree-sitter, and it's run-time customizable.

> I'm getting a parsing error where I don't expect it.

Apparently it errors out with simply
``` org
* A
b
```

~~This is the same issue as #14. It's defeating me at the moment :(~~ I'll never understand dynamic precedence. Fixed the problem though.

**Comment by kristijanhusak** [comment]
That fixed it, thanks.

**Comment by lukas-reineke** [comment]
Thank you for the explanation ❤️ 
this is what I was looking for. Conceptually this makes a lot of sense now. I'll have to actually build something to properly understand it I think.

**Comment by kristijanhusak** [comment]
@milisims Property drawer is sometimes not parsed when there's a plan date set. For example this content:
```
* TODO Testing
  DEADLINE: <2022-02-05 Sat 15:08>
  :PROPERTIES:
  :CATEGORY: Testing
  :END:
```

Gives this:
```
(document [0, 0] - [5, 0]
  (section [0, 0] - [5, 0]
    (headline [0, 0] - [1, 0]
      stars: (stars [0, 0] - [0, 1])
      item: (item [0, 2] - [0, 14]
        (expr [0, 2] - [0, 6])
        (expr [0, 7] - [0, 14])))
    (body [1, 2] - [5, 0]
      (paragraph [1, 2] - [2, 0]
        (expr [1, 2] - [1, 11])
        (expr [1, 12] - [1, 23])
        (expr [1, 24] - [1, 27])
        (expr [1, 28] - [1, 34]))
      (drawer [2, 2] - [5, 0]
        name: (expr [2, 3] - [2, 13])
        contents: (contents [3, 2] - [4, 0]
          (expr [3, 2] - [3, 12])
          (expr [3, 13] - [3, 20]))))))
```

**Comment by kristijanhusak** [comment]
Latest commit fixes it. Any chance to get a tagged release?

**Comment by ghost** [comment]
Seeing as orgmode-nvim uses the latest tagged revision (1c3eb533a9cf6800067357b59e03ac3f91fc3a54) - thought I'd chime in with an issue I've found:
```org
* Parent
** Child 1
SCHEDULED: <2022-02-17 Thu .+1d>
:LOGBOOK:
:END:
** Child 2
[2021-12-27 Mon] This is an `M-x org-time-stamp-inactive`
```

![image](https://user-images.githubusercontent.com/5359825/156918878-9108e865-9f79-48f6-8b49-7c442fcc304a.png)

**Comment by Symbolk** [comment]
Happy to see the progress! But is  https://github.com/tree-sitter/tree-sitter/issues/1508 (Sibling captures) closed?
